name: Build and Test

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21.0.2'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: 2.10.0

      - uses: actions/setup-node@v5
        with:
          cache: 'npm'

      - run: npm ci
          
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-

      - name: Run tests
        run: lein test

      - name: Generate coverage
        run: lein cloverage --coveralls --no-html

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: target/coverage/coveralls.json
